<?php
/**
 * @file
 * Code for the luggage_isudigitalrepo feature.
 */

include_once 'luggage_isudigitalrepo.features.inc';

/**
 * Implements hook_theme().
 */
function luggage_isudigitalrepo_theme($existing, $type, $theme, $path) {

  $themes = array();

  $themes['luggage_isudigitalrepo_bepress_widget'] = array(
    'variables' => array(
      'site_title' => "",
      'site_link' => ""
    ),
    'template' => 'luggage-isudigitalrepo-bepress-widget',
    'path' => drupal_get_path('module', 'luggage_isudigitalrepo') . '/templates',
  );

  $themes['views_view_fields__digital_repository'] = array(
    'variables' => array('view' => NULL, 'field' => NULL, 'row' => NULL),
    'template' => 'views-view-fields--digital-repository',
    'base hook' => 'views_view_fields',
    'path' => drupal_get_path('module', 'luggage_isudigitalrepo') . '/templates',
  );

  $themes['views_view_list__digital_repository__page'] = array(
    'variables' => array('view' => NULL, 'options' => NULL, 'rows' => NULL, 'title' => NULL),
    'template' => 'views-view-list--digital-repository--page',
    'base hook' => 'views_view_list',
    'path' => drupal_get_path('module', 'luggage_isudigitalrepo') . '/templates',
  );

  return $themes;
}


/**
 * Preprocess function for the luggage_isudigitalrepo_bepress_widget theme template
 */
function template_preprocess_luggage_isudigitalrepo_bepress_widget(&$variables) {

  if (!empty($variables['site_title'])) {
    $variables['site_title'] = drupal_json_encode($variables['site_title']);
  }

  if (!empty($variables['site_link'])) {
    $variables['site_link'] = drupal_json_encode($variables['site_link']);
  }

}

/*
 * Implements hook_block_info().
 */
function luggage_isudigitalrepo_block_info() {
  $blocks = array();
  $blocks['bepress_widget'] = array(
    'info' => t('ISU Digital Repository Publication Map'),
  );
  return $blocks;
}

/*
 * Implements hook_block_configure().
 */
function luggage_isudigitalrepo_block_configure($delta = '') {

  $form = array();

  switch ($delta) {

    case 'bepress_widget':

      $form['site_title'] = array(
        '#type' => 'textfield',
        '#title' => t('Site Title'),
        '#default_value' => variable_get('luggage_isudigitalrepo_bepress_widget_site_title', ''),
        '#maxlength' => 255,
        '#description' => t('site_title property value for the widget'),
        '#required' => TRUE,
        '#weight' => -18,
      );

      $form['site_link'] = array(
        '#type' => 'textfield',
        '#title' => t('Site Link'),
        '#default_value' => variable_get('luggage_isudigitalrepo_bepress_widget_site_link', ''),
        '#maxlength' => 255,
        '#description' => t('site_link property value for the widget'),
        '#required' => TRUE,
        '#weight' => -18,
      );

      break;

  }

  return $form;

}

/*
 * Implements hook_block_save().
 */
function luggage_isudigitalrepo_block_save($delta = '', $edit = array()) {

  switch ($delta) {

    case 'bepress_widget':

      variable_set('luggage_isudigitalrepo_bepress_widget_site_title', $edit['site_title']);
      variable_set('luggage_isudigitalrepo_bepress_widget_site_link', $edit['site_link']);

      break;

  }

}

/*
 * Implements hook_block_view().
 */
function luggage_isudigitalrepo_block_view($delta = '') {

  $block = array();

  switch ($delta) {

    case 'bepress_widget':

      $site_title = variable_get('luggage_isudigitalrepo_bepress_widget_site_title', '');

      if (empty($site_title)) {
        $site_title = variable_get('site_name', '');
      }

      $site_link = variable_get('luggage_isudigitalrepo_bepress_widget_site_link', '');

      if (!empty($site_title) && !empty($site_link)) {
        $block['subject'] = t('Recent Publications');
        $block['content'] = theme('luggage_isudigitalrepo_bepress_widget', array('site_title' => $site_title, 'site_link' => $site_link));
      }

      break;

  }

  return $block;

}


/**
 * Implements hook_feed_plugins().
 */
function luggage_isudigitalrepo_feeds_plugins() {
  $info = array();
  $info['FeedsISUDigitalRepositoryParser'] = array(
    'name' => 'ISU Digital Repository parser',
    'description' => 'Parse Dublin Core (oai_dc) metadata and document URLs from the ISU Digital Repository.',
    'handler' => array(
      'parent' => 'FeedsOAIParser',
      'class' => 'FeedsISUDigitalRepositoryParser',
      'file' => 'FeedsISUDigitalRepositoryParser.inc',
      'path' => drupal_get_path('module', 'luggage_isudigitalrepo') . '/plugins',
    ),
  );
  return $info;
}

/**
 * Implements hook_views_pre_render().
 */
function luggage_isudigitalrepo_preprocess_html(&$variables) {
  drupal_add_css(drupal_get_path('module', 'luggage_isudigitalrepo') . '/css/luggage_isudigitalrepo.css');
}